#!/usr/bin/env python3
# encoding: utf-8
import sys
import markovify
import tweepy
from util.get_twitter_auth import authorizeApp

def open_file(filename):
  with open(filename) as f:
    text = f.read()
    return text

def create_chain(text):
  return markovify.Text(text)

def post_to_twitter(message, api):
  api.update_status(message)

def write_message(text_model, api):
  message = (text_model.make_short_sentence(140))
  print(message)
  post_to_twitter(message, api)


if __name__ == "__main__":
  if len(sys.argv) != 2:
    print("Incorrect number of arguments")
    exit(1)
  file = open_file(sys.argv[1])
  model = create_chain(file)
  api = authorizeApp()
  write_message(model, api)
