#!/usr/bin/env python3
# encoding: utf-8
import os
import time
import schedule
import time
import random

COMMAND = r"./create_tweet 'data/welcome_nightvale.txt'"

def do_math():
  die = random.randint(1,10)
  return die % 3 == 0

def run_command():
  if do_math():
    status = os.system(COMMAND)
  else:
    status = "Math failed.."
  return status

def job():
  print("check log")
  with open("status_log.txt", "a+") as log:
    log.write("Initiating command\n")
    status = run_command()
    log.write("-"*100)
    log.write("\n")
    log.write("Command status = %s.\n" % status)

if __name__=="__main__":
  schedule.every(1).minutes.do(job)
  with open("status_log.txt", "a+") as log:
    log.write("Tweet scheduler started\n")
  while True:
      schedule.run_pending()
      time.sleep(1)
