#!/usr/bin/env python3
# encoding: utf-8
import os
import time
import schedule
import datetime
import random

COMMAND = r"./create_tweet 'data/welcome_nightvale.txt'"

def get_timestamp():
  current_dt = datetime.datetime.now()
  return current_dt.strftime("[%Y-%m-%d %H:%M:%S]: ")

def do_math():
  die = random.randint(1,10)
  return die % 3 == 0

def run_command():
  if do_math():
    status = os.system(COMMAND)
  else:
    status = "Math failed.."
  return status

def job():
  with open("status_log.txt", "a+") as log:
    log.write(get_timestamp() + "Initiating command\n")
    status = run_command()
    log.write("-"*100)
    log.write("\n")
    log.write("Command status = %s.\n" % status)

if __name__=="__main__":
  schedule.every(3).hours.do(job)
  with open("status_log.txt", "a+") as log:
    log.write(get_timestamp() + "Tweet scheduler started\n")
  while True:
      schedule.run_pending()
      time.sleep(1)
